In [17]:
import pandas as pd
import numpy as np

In [18]:
data_df=pd.read_csv('/home/leah/Downloads/realEstate.csv')

In [19]:
data_df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [20]:
#calculate correlation for all pairwise combinations
data_df['X3 distance to the nearest MRT station'].corr(data_df['X4 number of convenience stores'])

-0.6025191447226252

In [7]:
x=data_df.drop(['Y house price of unit area',],axis=1).values
y=data_df['Y house price of unit area'].values

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()
model

LinearRegression()

In [10]:
model.fit(x, y)

LinearRegression()

In [11]:
print('intercept:', model.intercept_)

intercept: -14038.079782924411

In [12]:
print('slope:', model.coef_)

slope: [-3.59350128e-03  5.07908732e+00 -2.70841959e-01 -4.52079011e-03
  1.12927749e+00  2.24672892e+02 -1.44235635e+01]

In [13]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[47.89494828 48.56266359 49.48549608 49.06033833 46.89537276 31.91889851
 39.33884835 47.54002053  9.81655865 35.48386229 34.29401738 53.78979552
 41.54535896 27.67273277 46.25647334 38.73649247 51.43047277 37.9292868
 47.38089493 48.26799893 35.95766929 50.11138559 29.50341213 48.5161202
 35.50368053 32.63559946 46.82956086 42.76561856 43.36789538 46.32719978
 13.89809241 41.15359321 31.29576969 47.00535857 47.72827054 33.70165743
 31.12724096 31.45055473 45.00438468 46.47306013 15.01052845 17.07419178
 37.12270337 40.76168072 48.22815789 40.29546715 47.30437819 38.02779522
 13.16548441 10.05136704 42.34410669 24.32725969 35.39205449 42.15990131
 46.01959847 23.86067762 43.89609878 46.45669327 14.0061475  41.22718249
 34.55078751 50.88818913 30.24001441 48.18696556 33.68817154 44.03927002
 47.57742051 47.58869518 43.67261577 45.65208957 54.76629818 35.51034432
 45.50794239 15.6859821  53.26095864 32.92408517 38.38559021 28.86900812
 33.30751556 28.52317152 45.21256577 38.31414837 46.28179096 25.07393289
 44.70150697 49.82764395 31.71110083 17.30337078 37.36839183 16.86502874
 43.09465602 39.00545839 28.6044496  24.0437536  35.37848586 44.66239021
 53.88390705 37.9163641  47.47664699 53.87312654 45.04857727 39.85100338
 47.84253451 44.27280134 35.85292458 48.99267175 48.26523973 31.98796974
 36.61450404 37.14443892 45.42453199 45.26352473 34.29717754 43.60305768
 43.7312956  38.86000346  1.57339504 13.60552276 34.13415415 47.76857932
 42.34578006 43.95227005 40.72957174 44.36615341 47.36421647 48.18652732
 35.51336144 49.23813576 37.40997749 43.72987733 45.06399435 36.64381765
 40.78760979 48.02423672 36.95290126 30.99165286 44.26607781 45.68405197
 38.66870332 39.84629666 46.53168074 40.12197202 42.10184977 43.87321302
 30.66649095 46.42143493 40.89575164 47.28340415 15.71105362 40.45417265
 40.65918442 54.78428856 31.88043057 43.68324631 16.64104194 15.39131499
 26.92424723 42.40301126 45.40262422 39.59722152 47.44684963 41.76007483
 13.04673621 47.24371905 41.25263287 35.33420969 51.73965516 45.49878054
 37.20078608 30.99825899 12.828356   48.28598252 54.39976105 37.38882862
 51.83256968 36.07425087 13.09492322 44.88240547 45.82417929 39.58428678
  9.33256004 51.66705113 33.88755047 16.11533876 21.89289591 30.53528898
 30.06539486 22.33345878 42.35769292 13.71666667 43.87928016 39.31235465
 38.52994282 48.43046704 16.07383281 40.06010093 37.70890345 42.58760466
 39.99142061 46.43335231 33.6531829  47.98142922 33.42055319 43.50668743
 28.07398386 37.19067821 50.30698637 33.96764999 28.85350758 41.11782099
 49.48869435 43.92961419 37.45170161 51.82122063 35.53615463 46.56025468
 32.28252474 41.33338224 43.18213617 42.33405457 44.84860447 38.98695166
 48.94114972 38.53111622 41.81493947 48.24874144 13.55669553 43.36627911
 34.21967688 27.06574187 36.28806102 12.98787983 11.96157602 44.21212738
 34.06967242 43.39734438 54.7935161  38.03870795 37.66263951 34.54594319
 33.27256718 46.96842529 33.83908337 46.42202055 38.56332214 45.58491293
 43.60668616 31.4118217  30.98006727  7.27503152 39.4551561  23.56904824
 50.49255483 25.87841541 47.17466171  8.56156798 37.48024539 39.25251736
 51.40905305 32.46443054 37.19180668 29.60430974 44.4831901  35.77499543
 39.75771897 40.00527049 33.73920908 36.41225209 45.60860351 32.03401547
 42.11610725 43.77049754 39.76284104 42.06368717 42.38683218 47.3480626
 37.02140761 30.92690548 43.64393862 40.33272768 47.79082526 53.52309421
 31.37924952 32.57481505 43.16676242 36.16883426 50.79701913 36.9547949
 47.75324821 47.04074981 30.67741002 45.21625484 38.75913878 42.51466978
 44.88991696 30.37617435 41.75333582 33.67049306 14.93513112 47.32401789
 44.95692717 29.02511658 31.06705967 32.69618137 34.29406952 45.09054545
 42.03855504 20.65811675 46.72201172 24.79144224 31.61798325 40.19083191
 44.28679657 45.91065467 46.81118105 35.82554323 45.53747765 37.24834958
 54.41579206 35.11525237 11.63335437 41.45581076 39.81105481 43.61206926
 30.47863401 39.28928679 48.28864416 44.18931987 33.78438948 12.84370049
 23.99893288 12.04949353 32.87535102 43.01309772 39.06466567 41.48687004
 37.02784194 35.17133461 41.64365353 50.08938108 34.04357246 37.97929027
 49.38017962 42.14943189 27.7906669  39.75908064 33.9922189  10.04209091
 46.65869239 42.9556017  40.69815138 32.37927263 25.89210333 35.81897617
 31.52701826 48.41881747 39.49907544 52.23796284 47.34924152 28.36167868
 45.08158447 39.59771905 43.78230328 49.08747827 41.63881627 29.59936196
 25.38495347 30.07693486 39.92029811 27.05782984 43.24688438 44.3300641
 38.97167134 43.34746698 47.57541992 29.94968396 33.53919606 48.67162339
 39.85025044 50.54759606 46.6595728  54.22700224 13.24250319 36.35602819
 12.22189473 50.65676154 40.45487558 30.74485985 33.86514036 39.85574227
 44.16024904 31.05324567 37.47978792 41.60709372 15.24500036 38.70022607
 27.26685608 44.4856823  33.46013903 39.20678333 40.19194731 32.47335135
 38.72953552 44.1291934  45.95039226 36.99902313 48.9133769  25.75798374
 31.24696162 13.65744228 49.16290573 46.07582217 43.91773036 53.13924719]

In [14]:
x_new = np.arange(35).reshape((-1, 7))
print(x_new)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

In [15]:
y_new = model.predict(x_new)
print(y_new)

[-12992.21575158 -11478.96459036  -9965.71342913  -8452.4622679
  -6939.21110668]

In [16]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.5833632616324598